// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxJHbF6VRVmYJzAB_XsYeVNPgWj8LsJgM',
    appId: '1:123456789:web:abc123def456',
    messagingSenderId: '123456789',
    projectId: 'grace-notes-app',
    authDomain: 'grace-notes-app.firebaseapp.com',
    storageBucket: 'grace-notes-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu8N7lyVgzUAtirM8ZgQXdr-mQJhbYcMk',
    appId: '1:1090241694132:android:6ff78b43edee372150cae1',
    messagingSenderId: '1090241694132',
    projectId: 'grace-notes-98ebe',
    storageBucket: 'grace-notes-98ebe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxJHbF6VRVmYJzAB_XsYeVNPgWj8LsJgM',
    appId: '1:123456789:ios:abc123def456',
    messagingSenderId: '123456789',
    projectId: 'grace-notes-app',
    storageBucket: 'grace-notes-app.appspot.com',
    iosBundleId: 'com.example.graceNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxJHbF6VRVmYJzAB_XsYeVNPgWj8LsJgM',
    appId: '1:123456789:macos:abc123def456',
    messagingSenderId: '123456789',
    projectId: 'grace-notes-app',
    storageBucket: 'grace-notes-app.appspot.com',
    iosBundleId: 'com.example.graceNotes',
  );
}